spring:
  application:
    name: launchpad

  datasource:
    url: jdbc:postgresql://localhost:5432/biolab
    username: biolab
    password: biolab

  liquibase:
    change-log: db/changelog/biolab.changelog.yml