spring:
  application:
    name: launchpad
  security:
    user:
      name: biolab
      password: biolab
      roles: ADMIN

  datasource:
    url: jdbc:postgresql://localhost:5432/biolab
    username: biolab
    password: biolab

  liquibase:
    change-log: db/changelog/biolab.changelog.yml
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true

aws:
  s3:
    endpoint: http://localhost:4566
    bucket: biolab-resources
    region: us-east-1
    access-key: test
    secret-key: test